language: objective-c

branches:
  only:
  - master

xcode_project: Announce.xcodeproj
xcode_scheme: Announce-iOS
osx_image: xcode9.0
xcode_sdk: iphonesimulator8.3

script:
- pod lib lint Announce.podspec
- xcodebuild clean build test -workspace Announce.xcworkspace -scheme Announce-iOS -destination "platform=iOS Simulator,name=iPhone 5s,OS=8.3"
